config/routes.rb
Rails.application.routes.draw do

  #get 'order/create'

  #get 'order/address_confirm'

  #get 'order/show'
  resources :order, only: [:index,:create] do
    collection do
      get 'address_confirm'
      post 'address_change'
    end
  end

  devise_for :customers

  resources :home, only: [:index]

  resources :cart, only: [:show] do
    collection do
      post 'add_item'
      post 'update_item'
    end
  end

  #Casein routes
  namespace :casein do
      resources :items
      resources :customers
  end

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/casein/customers_controller.rb
# Scaffolding generated by Casein v5.3.0.0

module Casein
  class CustomersController < Casein::CaseinController
    skip_before_action :authenticate_customer!
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]
  
    def index
      @casein_page_title = 'Customers'
      @customers = Customer.order(sort_order(:mail)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View customer'
      @customer = Customer.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new customer'
      @customer = Customer.new
    end

    def create
      @customer = Customer.new customer_params

      if @customer.save
        flash[:notice] = 'Customer created'
        redirect_to casein_customers_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new customer'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update customer'

      @customer = Customer.find params[:id]

      if @customer.update_attributes customer_params
        flash[:notice] = 'Customer has been updated'
        redirect_to casein_customers_path
      else
        flash.now[:warning] = 'There were problems when trying to update this customer'
        render action: :show
      end
    end

    def destroy
      @customer = Customer.find params[:id]

      @customer.destroy
      flash[:notice] = 'Customer has been deleted'
      redirect_to casein_customers_path
    end

    private

    def customer_params
      params.require(:customer).permit(:mail, :address, :password, :name)
    end
  end
end

app/controllers/casein/items_controller.rb
# Scaffolding generated by Casein v5.3.0.0

module Casein
  class ItemsController < Casein::CaseinController
    skip_before_action :authenticate_customer!
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]
  
    def index
      @casein_page_title = 'Items'
      @items = Item.order(sort_order(:name)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View item'
      @item = Item.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new item'
      @item = Item.new
    end

    def create
      @item = Item.new item_params

      if @item.save
        flash[:notice] = 'Item created'
        redirect_to casein_items_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new item'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update item'

      @item = Item.find params[:id]

      if @item.update_attributes item_params
        flash[:notice] = 'Item has been updated'
        redirect_to casein_items_path
      else
        flash.now[:warning] = 'There were problems when trying to update this item'
        render action: :show
      end
    end

    def destroy
      @item = Item.find params[:id]

      @item.destroy
      flash[:notice] = 'Item has been deleted'
      redirect_to casein_items_path
    end

    private

    def item_params
      params.require(:item).permit(:name, :price, :description, :hide_flg, :display_order)
    end
  end
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    
    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'Casein'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'casein/casein.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://www.caseincms.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@caseincms.com'
    end
  
    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for controller: :items, action: :index
    end
  
    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end
  
    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom]
    end

     # A list of stylesheets to include in the authentication layout. Do not remove the core casein/login, but you can change the load order, if required.
    def casein_config_auth_stylesheet_includes
      %w[casein/login casein/auth_custom]
    end
  
    # A list of JavaScript files to includein the authentication layout. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_auth_javascript_includes
      %w[casein/casein casein/auth_custom]
    end
    
  end
end

app/views/casein/customers/_form.html.haml
/ Scaffolding generated by Casein v5.3.0.0
.row
  .col-lg-6
    = casein_text_field f, f.object, :name
  .col-lg-6
    = casein_text_field f, f.object, :email
.row
  .col-lg-6
    = casein_text_field f, f.object, :address

app/views/casein/customers/_table.html.haml
/ Scaffolding generated by Casein v5.3.0.0
%table.table.table-striped.table-hover.table-condensed
  %thead
    %tr
      %th= casein_sort_link "お名前", :name
      %th= casein_sort_link "メールアドレス", :email
      %th= casein_sort_link "送付先住所", :address
      %th= casein_sort_link "作成日時", :created_at
      %th  
  - customers.each do |customer|
    %tr
      %td= casein_table_cell_link customer.name, casein_customer_path(customer)
      %td= casein_table_cell_link customer.email, casein_customer_path(customer)
      %td= casein_table_cell_link customer.address, casein_customer_path(customer)
      %td= casein_table_cell_link customer.created_at.strftime('%Y年%m月%d日 %H:%M'), casein_customer_path(customer)
      %td.delete
        = link_to(casein_show_row_icon("trash"), casein_customer_path(customer), method: :delete, data: { confirm: "Are you sure you want to delete this customer?" })

app/views/casein/customers/index.html.haml
/ Scaffolding generated by Casein v5.3.0.0
%h2
  Customers#{casein_pagination_details @customers}
= render partial: 'casein/customers/table', locals: { customers: @customers }
.text-center
  = will_paginate @customers

app/views/casein/customers/new.html.haml
/ Scaffolding generated by Casein v5.3.0.0
%h2 Add a new customer
= form_for @customer, url: casein_customers_path do |f|
  = render partial: 'casein/customers/form', locals: { f: f }
  %p.submits
    = link_to 'Cancel', casein_customers_path, class: 'btn btn-mini btn-danger'
    = f.submit "Add new customer", class: "btn btn-mini btn-primary"
= content_for :sidebar do
  %li= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_customers_path

app/views/casein/customers/show.html.haml
/ Scaffolding generated by Casein v5.3.0.0
%h2 View customer
= form_for @customer, url: casein_customer_path(@customer) do |f|
  = render partial: 'casein/customers/form', locals: { f: f }
  %p.submits
    = link_to 'Cancel', casein_customers_path, class: 'btn btn-mini btn-danger'
    = f.submit "Save changes", class: "btn btn-mini btn-primary"
= content_for :sidebar do
  %li= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_customers_path