config/routes.rb
Rails.application.routes.draw do

  #get 'order/create'

  #get 'order/address_confirm'

  #get 'order/show'
  resources :order, only: [:index,:create] do
    collection do
      get 'address_confirm'
      post 'address_change'
    end
  end

  devise_for :customers

  resources :home, only: [:index]

  resources :cart, only: [:show] do
    collection do
      post 'add_item'
      post 'update_item'
    end
  end

  #Casein routes
  namespace :casein do
      resources :items
      resources :customers
  end

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/casein/customers_controller.rb
# Scaffolding generated by Casein v5.3.0.0

module Casein
  class CustomersController < Casein::CaseinController
    skip_before_action :authenticate_customer!
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]
  
    def index
      @casein_page_title = 'Customers'
      @customers = Customer.order(sort_order(:mail)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View customer'
      @customer = Customer.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new customer'
      @customer = Customer.new
    end

    def create
      @customer = Customer.new customer_params

      if @customer.save
        flash[:notice] = 'Customer created'
        redirect_to casein_customers_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new customer'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update customer'

      @customer = Customer.find params[:id]

      if @customer.update_attributes customer_params
        flash[:notice] = 'Customer has been updated'
        redirect_to casein_customers_path
      else
        flash.now[:warning] = 'There were problems when trying to update this customer'
        render action: :show
      end
    end

    def destroy
      @customer = Customer.find params[:id]

      @customer.destroy
      flash[:notice] = 'Customer has been deleted'
      redirect_to casein_customers_path
    end

    private

    def customer_params
      params.require(:customer).permit(:mail, :address, :password, :name)
    end
  end
end

app/controllers/casein/items_controller.rb
# Scaffolding generated by Casein v5.3.0.0

module Casein
  class ItemsController < Casein::CaseinController
    skip_before_action :authenticate_customer!
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]
  
    def index
      @casein_page_title = 'Items'
      @items = Item.order(sort_order(:name)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View item'
      @item = Item.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new item'
      @item = Item.new
    end

    def create
      @item = Item.new item_params

      if @item.save
        flash[:notice] = 'Item created'
        redirect_to casein_items_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new item'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update item'

      @item = Item.find params[:id]

      if @item.update_attributes item_params
        flash[:notice] = 'Item has been updated'
        redirect_to casein_items_path
      else
        flash.now[:warning] = 'There were problems when trying to update this item'
        render action: :show
      end
    end

    def destroy
      @item = Item.find params[:id]

      @item.destroy
      flash[:notice] = 'Item has been deleted'
      redirect_to casein_items_path
    end

    private

    def item_params
      params.require(:item).permit(:name, :price, :description, :hide_flg, :display_order)
    end
  end
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    
    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'Casein'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'casein/casein.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://www.caseincms.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@caseincms.com'
    end
  
    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for controller: :items, action: :index
    end
  
    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end
  
    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom]
    end

     # A list of stylesheets to include in the authentication layout. Do not remove the core casein/login, but you can change the load order, if required.
    def casein_config_auth_stylesheet_includes
      %w[casein/login casein/auth_custom]
    end
  
    # A list of JavaScript files to includein the authentication layout. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_auth_javascript_includes
      %w[casein/casein casein/auth_custom]
    end
    
  end
end

app/views/casein/items/_form.html.haml
/ Scaffolding generated by Casein v5.3.0.0
.row
  .col-lg-6
    = casein_text_field f, f.object, :name
  .col-lg-6
    = casein_text_field f, f.object, :price
.row
  .col-lg-6
    = casein_text_area f, f.object, :description
  .col-lg-6
    = casein_check_box f, f.object, :hide_flg
.row
  .col-lg-6
    = casein_text_field f, f.object, :display_order
  .col-lg-6

app/views/casein/items/_table.html.haml
/ Scaffolding generated by Casein v5.3.0.0
%table.table.table-striped.table-hover.table-condensed
  %thead
    %tr
      %th= casein_sort_link "Name", :name
      %th= casein_sort_link "Price", :price
      %th= casein_sort_link "Description", :description
      %th= casein_sort_link "Hide flg", :hide_flg
      %th= casein_sort_link "Display order", :display_order
      %th  
  - items.each do |item|
    %tr
      %td= casein_table_cell_link item.name, casein_item_path(item)
      %td= casein_table_cell_link item.price, casein_item_path(item)
      %td= casein_table_cell_link item.description, casein_item_path(item)
      %td= casein_table_cell_link item.hide_flg, casein_item_path(item)
      %td= casein_table_cell_link item.display_order, casein_item_path(item)
      %td.delete
        = link_to(casein_show_row_icon("trash"), casein_item_path(item), method: :delete, data: { confirm: "Are you sure you want to delete this item?" })

app/views/casein/items/index.html.haml
/ Scaffolding generated by Casein v5.3.0.0
%h2
  Items#{casein_pagination_details @items}
= render partial: 'casein/items/table', locals: { items: @items }
.text-center
  = will_paginate @items
= content_for :sidebar do
  %li= link_to "#{casein_show_icon "plus-sign"}Add a new item".html_safe, new_casein_item_path

app/views/casein/items/new.html.haml
/ Scaffolding generated by Casein v5.3.0.0
%h2 Add a new item
= form_for @item, url: casein_items_path do |f|
  = render partial: 'casein/items/form', locals: { f: f }
  %p.submits
    = link_to 'Cancel', casein_items_path, class: 'btn btn-mini btn-danger'
    = f.submit "Add new item", class: "btn btn-mini btn-primary"
= content_for :sidebar do
  %li= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_items_path

app/views/casein/items/show.html.haml
/ Scaffolding generated by Casein v5.3.0.0
%h2 View item
= form_for @item, url: casein_item_path(@item) do |f|
  = render partial: 'casein/items/form', locals: { f: f }
  %p.submits
    = link_to 'Cancel', casein_items_path, class: 'btn btn-mini btn-danger'
    = f.submit "Save changes", class: "btn btn-mini btn-primary"
= content_for :sidebar do
  %li= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_items_path